# Generated by Django 4.2.6 on 2023-12-28 12:10

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import questionnaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeOfDating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=questionnaire.models.MediaPath.directory_path_datatime),
        ),
        migrations.AddField(
            model_name='profile',
            name='PurposeOfDating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.purposeofdating'),
        ),
    ]
