# Generated by Django 4.2.6 on 2023-12-28 12:20

from django.db import migrations, models
import imagekit.models.fields
import questionnaire.models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_purposeofdating_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=questionnaire.models.MediaPath.directory_path_datatime),
        ),
        migrations.AlterField(
            model_name='purposeofdating',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
